workflows:
  react-native-android:
    name: React Native Android
    triggering:
      events:
        - push
    scripts:
      - name: Build APK
        script: flutter pub get && flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
