workflows:
  expo-android:
    name: Build Android with Expo
    triggering:
      events:
        - push
    scripts:
      - name: Install Node dependencies
        script: npm install
      - name: Install Expo CLI
        script: npm install -g expo-cli
      - name: Build APK with Expo
        script: expo build:android --non-interactive --release-channel=default
    artifacts:
      - "*.apk"
